[package]
name = "spmc"
version = "0.2.2"
description = "Simple SPMC channel"
keywords = ["spmc", "channel", "queue"]
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/seanmonstar/spmc"
documentation = "https://docs.rs/spmc"
